version: "3.8"

services:
  gateway:
    image: tiangolo/uvicorn-gunicorn-fastapi
    volumes:
      - ./gateway:/app
    ports:
      - "8000:80"
    depends_on:
      - auth
      - user
      - product

  auth:
    image: tiangolo/uvicorn-gunicorn-fastapi
    volumes:
      - ./auth-service:/app

  user:
    image: tiangolo/uvicorn-gunicorn-fastapi
    volumes:
      - ./user-service:/app

  product:
    image: tiangolo/uvicorn-gunicorn-fastapi
    volumes:
      - ./product-service:/app
