version: "3.8"

services:
  gateway:
    build: ./gateway
    ports:
      - "8000:80"
    depends_on:
      - auth
      - user
      - product

  auth:
    build: ./auth-service

  user:
    build: ./user-service

  product:
    build: ./product-service
