name: Microservices CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install deps (gateway)
      run: |
        cd gateway
        pip install -r requirements.txt

    - name: Basic test (gateway)
      run: |
        cd gateway
        python -c "import main"

  docker-build-push:
    needs: build-test
    runs-on: ubuntu-latest

    steps:
    - name: Check secrets existence
      run: |
        if [ -z "${{ secrets.DOCKER_USERNAME }}" ]; then
          echo "DOCKER_USERNAME is EMPTY"
          exit 1
        fi

        if [ -z "${{ secrets.DOCKER_PASSWORD }}" ]; then
          echo "DOCKER_PASSWORD is EMPTY"
          exit 1
        fi

        echo "Secrets are present"

    - name: Checkout
      uses: actions/checkout@v4

    - name: Login Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build & Push Gateway
      run: |
        docker build -t danieltsonkov/gateway:latest ./gateway
        docker push danieltsonkov/gateway:latest

    - name: Build & Push Auth
      run: |
        docker build -t danieltsonkov/auth:latest ./auth-service
        docker push danieltsonkov/auth:latest

    - name: Build & Push User
      run: |
        docker build -t danieltsonkov/user:latest ./user-service
        docker push danieltsonkov/user:latest

    - name: Build & Push Product
      run: |
        docker build -t danieltsonkov/product:latest ./product-service
        docker push danieltsonkov/product:latest
